### PR TITLE
added quiet/silent unchanged mode, regarding #47

### PR DESCRIPTION
**Pull request by zaanposni**
Hey,
I added a `--quiet` flag that will stop all output if there is no DNS change, error, warning, etc.

These changes are done regarding #47.

The script is still usable with `--debug`.
If a change @ CloudFlare is done or an error is thrown it will log all messages as before.

I am not 100% happy with my implementation although I do not know how to do it better. I tried using custom LogLevels but that would mean that we lose all messages until the very point in execution where the script knows a DNS change occures.

I am open for suggestions on how to improve my implementation!

### CODE REVIEW

**Comment by robobenklein** [comment]
Using standard python logging levels, `--quiet` could be warnings and up only, and `--silent` could be errors and up only. ( https://docs.python.org/3/library/logging.html )

I think if there's an error the user will run the program again in debug mode anyways, so I don't think storing / buffering the logs is worth the logic complexity.

Perhaps as simple as creating a logger object and doing `setLevel` when arguments get parsed.

**Comment by zaanposni** [comment]
I also thought about using log levels.
E.g. if you add a custom log level `change` on level 21 (INFO is 20 and WARNING is 30), the user will receive his change notification but not the normal logging (INFO Level) that comes with a DNS change.
Furthermore, debug and quiet mode could not be used together.

I am happy with both ways. If a new log level was your request for #47, I can implement it for sure.

**Comment by robobenklein** [comment]
I think it would be reasonable to assume that debug and quiet mode would conflict, and one should have priority over the other.

I like the idea of adding the `change` level, it sounds like it would accomplish the goal of only notifying on changes, warnings, or errors. This fits my use case, I haven't heard much opinions from others.

**Comment by LINKIWI** [comment]
Thanks, I think we can probably make this much simpler and do away with the global variables by simply not printing if the quiet flag is set.

I like the proposed idea of using the Python logging module and just setting the level to silent if the flag calls for it, so that there doesn't need extra logic to deal with that.

**Comment by zaanposni** [comment]
then i would suggest a compromise: 
`--silent` flag for no output at all 
`--silent-unchanged` for no output except dns changes, warnings and errors.

If there are no objections, I would adjust my changes accordingly

**Comment by LINKIWI** [comment]
Is there really a need to have --silent-unchanged? Sounds like it is just normal behavior at a warn instead of info log level.

**Comment by zaanposni** [comment]
Thought thats what @robobenklein requested. more or less.

**Comment by zaanposni** [comment]
Will open a new PR.

**Pull request closed without merging**
