### PR TITLE
Cloudflare Proxy/Protection Fix (final)

### PR DESCRIPTION
**Pull request by ghost**
Fix for issue https://github.com/LINKIWI/cloudflare-ddns-client/issues/18

### CODE REVIEW

**Comment by LINKIWI** [comment]
Please see https://github.com/LINKIWI/cloudflare-ddns-client/pull/20#discussion_r291217120

**Comment by itsKastel** [comment]
This would be a nice change if you could merge it please.

**Comment by marvinjuette** [comment]
I think this pull request isn't that optimal because it sets the proxied value always to true an not to the value set by thr user

**Comment by LINKIWI** [comment]
Closing in favor of #28

**Pull request closed without merging**
